// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klqgbprlxrpxrqezmpax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtscWdicHJseHJweHJxZXptcGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODAyNDIsImV4cCI6MjA2MTg1NjI0Mn0.Fq4B3L-iPjrOf9oic4L-bBJ-36jgacS56JhfMTLvPrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);